language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rangular' ]; then cd .. && eval "mv $currentfolder generator-rangular" && cd generator-rangular; fi

